import React from "react";

const ROADMAP_ITEMS = [
  {
    title: "AI Meme Engine",
    description: "Instant, match-aware memes generated by Gemini. Because some failures deserve a picture.",
    icon: "🎨",
    tag: "Prototyping"
  },
  {
    title: "User Roast Hub",
    description: "Think you're funnier? Post your own burns, get 'Flames' from the community, and lead the board.",
    icon: "🎤",
    tag: "Planned"
  },
  {
    title: "Social Rivalries",
    description: "Follow your favorite roasters and team rivals. Build your reputation as the salt-king of the season.",
    icon: "🤝",
    tag: "Planned"
  },
  {
    title: "Live Heatmap",
    description: "A real-time visualizer showing which team is currently being roasted the most across the web.",
    icon: "📈",
    tag: "Concept"
  }
];

export function RoadmapSection() {
  return (
    <section className="relative py-24 px-6 md:px-16 bg-[#FCFBF7] text-[#1A1A1A] overflow-hidden">
      {/* Architectural vertical accent lines — consistent with other sections */}
      <div className="absolute left-[5%] top-0 bottom-0 w-px bg-[#1A1A1A]/4 hidden xl:block" aria-hidden="true" />
      <div className="absolute right-[5%] top-0 bottom-0 w-px bg-[#1A1A1A]/4 hidden xl:block" aria-hidden="true" />

      <div className="mx-auto max-w-6xl relative z-10">
        <header className="mb-16">
          <p className="mb-3 text-[0.68rem] font-black tracking-[0.25em] uppercase text-[#1A1A1A]/30">
            Evolution · The Roadmap
          </p>
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
            <h2 className="text-4xl md:text-6xl font-black tracking-tighter leading-[0.9] text-[#1A1A1A]">
              What&apos;s Cooking <br />
              <span className="text-[#F59E0B]">in the Kitchen?</span>
            </h2>
            <p className="max-w-xs text-[0.8rem] font-bold text-[#1A1A1A]/40 leading-relaxed uppercase tracking-wide">
              We&apos;re just getting started. Here&apos;s a glimpse into the next phase of Bails on Fire.
            </p>
          </div>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {ROADMAP_ITEMS.map((item, index) => (
            <div 
              key={index}
              className="group p-8 rounded-2xl bg-white border border-[#1A1A1A]/5 shadow-sm transition-all hover:-translate-y-1 hover:shadow-md"
            >
              <div className="text-3xl mb-6">{item.icon}</div>
              
              <div className="inline-flex items-center px-2.5 py-0.5 rounded-full bg-[#1A1A1A]/5 border border-[#1A1A1A]/5 text-[0.6rem] font-black uppercase tracking-widest text-[#1A1A1A]/40 mb-4">
                {item.tag}
              </div>

              <h3 className="text-xl font-black tracking-tight mb-3 text-[#1A1A1A]">
                {item.title}
              </h3>
              
              <p className="text-[0.82rem] leading-relaxed text-[#1A1A1A]/50 font-medium">
                {item.description}
              </p>
            </div>
          ))}
        </div>

        {/* Subtle bottom note */}
        <div className="mt-20 pt-10 border-t border-[#1A1A1A]/5 flex flex-col md:flex-row items-center justify-between gap-6">
          <p className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-[#1A1A1A]/20">
            Est. Arrival: Mid-Season 2026
          </p>
          <div className="flex items-center gap-4">
             <div className="w-2.5 h-2.5 rounded-full bg-[#F59E0B] animate-pulse" />
             <span className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-[#1A1A1A]/40">Core Engine Live</span>
          </div>
        </div>
      </div>
    </section>
  );
}
